@description('The name of the CDN profile')
param cdnProfileName string

@description('The location for the CDN profile')
param location string = 'global'

@description('The environment (dev, staging, prod)')
param environment string

@description('The origin hostname (e.g., Static Web App hostname)')
param originHostname string

@description('Custom domain for CDN (optional)')
param customDomain string = ''

// CDN Profile - Premium Microsoft tier - INTENTIONALLY INEFFICIENT
// Standard tier or no CDN would suffice for a demo application
resource cdnProfile 'Microsoft.Cdn/profiles@2023-05-01' = {
  name: cdnProfileName
  location: location
  sku: {
    name: 'Premium_AzureFrontDoor'  // INTENTIONALLY INEFFICIENT - Premium tier
  }
  properties: {
    originResponseTimeoutSeconds: 60
  }
  tags: {
    Environment: environment
    Application: 'HikePlanner'
    CostCenter: 'Demo'
    CostOptimization: 'Inefficient-Demo'
    ServiceTier: 'Network'
    Purpose: 'Unnecessary-CDN'
    MonthlyCost: '$20'
    OptimizationPotential: 'Remove - Static Web App has built-in CDN'
  }
}

// CDN Endpoint - INTENTIONALLY INEFFICIENT
resource cdnEndpoint 'Microsoft.Cdn/profiles/afdendpoints@2023-05-01' = {
  parent: cdnProfile
  name: '${cdnProfileName}-endpoint'
  location: location
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
  tags: {
    Environment: environment
    Application: 'HikePlanner'
    CostCenter: 'Demo'
    CostOptimization: 'Inefficient-Demo'
    ServiceTier: 'Network'
  }
}

// Origin Group for load balancing (unnecessary for single origin)
resource originGroup 'Microsoft.Cdn/profiles/origingroups@2023-05-01' = {
  parent: cdnProfile
  name: 'default-origin-group'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 50
    }
    healthProbeSettings: {
      probePath: '/'
      probeRequestType: 'HEAD'
      probeProtocol: 'Https'
      probeIntervalInSeconds: 100
    }
    sessionAffinityState: 'Disabled'
  }
}

// Origin - pointing to the Static Web App
resource origin 'Microsoft.Cdn/profiles/origingroups/origins@2023-05-01' = {
  parent: originGroup
  name: 'webapp-origin'
  properties: {
    hostName: originHostname
    httpPort: 80
    httpsPort: 443
    originHostHeader: originHostname
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
}

// Route from endpoint to origin
resource route 'Microsoft.Cdn/profiles/afdendpoints/routes@2023-05-01' = {
  parent: cdnEndpoint
  name: 'default-route'
  properties: {
    originGroup: {
      id: originGroup.id
    }
    supportedProtocols: [
      'Http'
      'Https'
    ]
    patternsToMatch: [
      '/*'
    ]
    forwardingProtocol: 'HttpsOnly'
    linkToDefaultDomain: 'Enabled'
    httpsRedirect: 'Enabled'
    enabledState: 'Enabled'
  }
  dependsOn: [
    origin
  ]
}

// WAF Policy - Adds extra cost - INTENTIONALLY INEFFICIENT
resource wafPolicy 'Microsoft.Cdn/profiles/securitypolicies@2023-05-01' = {
  parent: cdnProfile
  name: '${cdnProfileName}-waf'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: firewallPolicy.id
      }
      associations: [
        {
          domains: [
            {
              id: cdnEndpoint.id
            }
          ]
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

// Firewall Policy for WAF
resource firewallPolicy 'Microsoft.Network/frontdoorwebapplicationfirewallpolicies@2022-05-01' = {
  name: '${replace(cdnProfileName, '-', '')}waf'
  location: location
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: 'Prevention'
      requestBodyCheck: 'Enabled'
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.0'
        }
      ]
    }
  }
  tags: {
    Environment: environment
    Application: 'HikePlanner'
    CostCenter: 'Demo'
    CostOptimization: 'Inefficient-Demo'
    ServiceTier: 'Security'
  }
}

@description('The resource ID of the CDN profile')
output cdnProfileId string = cdnProfile.id

@description('The name of the CDN profile')
output cdnProfileName string = cdnProfile.name

@description('The CDN endpoint hostname')
output cdnEndpointHostname string = cdnEndpoint.properties.hostName

@description('The CDN endpoint URL')
output cdnEndpointUrl string = 'https://${cdnEndpoint.properties.hostName}'

@description('Cost optimization summary for CDN')
output costOptimizationSummary object = {
  currentCost: 20
  optimizedCost: 0
  savings: 20
  savingsPercentage: 100
  recommendation: 'Remove CDN - Azure Static Web Apps has built-in global CDN'
  inefficiencies: [
    'Premium Azure Front Door tier for demo app'
    'WAF enabled when not required for demo'
    'Redundant CDN layer over Static Web Apps built-in CDN'
    'Global distribution for single-region demo'
  ]
}
